project:
  type: website

website:
  title: "OSU CoF Intro2R workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - day1.qmd
      - day2.qmd
      - day3.qmd
      - day4.qmd
      - day5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



