project:
  type: website

website:
  title: "CoF-intro2R-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - day1.qmd
      - day4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



